# Generated by Django 5.2.17 on 2026-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_group',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
